services:
  keycloak:
    #latest keycloak is 16.1.1 of this image
    image: jboss/keycloak:16.1.1
    env_file: .env
    restart: unless-stopped
    volumes:
      - data:/opt/jboss/keycloak/standalone/data/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 30s
      timeout: 20s
      retries: 3
    labels:
      - traefik.http.routers.keycloak.rule=Host(`${KEYCLOAK_DOMAIN}`)
      - traefik.http.services.keycloak.loadbalancer.server.port=8080
      - traefik.http.routers.keycloak.tls=true
      - traefik.http.routers.keycloak.tls.certresolver=letsencrypt

volumes:
  data: