services:
  keycloak:
    #latest keycloak is 16.1.1 of this image
    image: jboss/keycloak:16.1.1
    restart: unless-stopped
    volumes:
      - data:/opt/jboss/keycloak/standalone/data/
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/auth/"]
      interval: 30s
      timeout: 5s
      retries: 6
    environment:
      DB_VENDOR: h2
      KEYCLOAK_FRONTEND_URL: https://${KEYCLOAK_DOMAIN}/auth
      KEYCLOAK_USER: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    labels:
      - traefik.http.routers.keycloak.rule=Host(`${KEYCLOAK_DOMAIN}`)
      - traefik.http.services.keycloak.loadbalancer.server.port=8080
      - traefik.http.routers.keycloak.tls=true
      - traefik.http.routers.keycloak.tls.certresolver=letsencrypt

volumes:
  data: