services:
  traefik:
    # Enables the web UI and tells Traefik to listen to docker
    command: |
       --api.insecure=true
       --providers.docker=true
       --entrypoints.web.address=:80
       --entrypoints.websecure.address=:443
       --certificatesresolvers.letsencrypt.acme.email=${USER_EMAIL}
       --certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme.json
       --certificatesresolvers.letsencrypt.acme.httpchallenge=true
       --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
    ports:
      # The HTTP port
      - "80:80"
      # The HTTPS port
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"