services:
  minio:
    image: minio/minio:latest
    entrypoint: sh
    command: -c 'minio server /data --console-address ":9001"'
    restart: unless-stopped
    volumes:
      - data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "-q", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USERNAME}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    labels:
      - traefik.http.routers.minio.service=minio
      - traefik.http.routers.minio.rule=Host(`${MINIO_DOMAIN}`)
      - traefik.http.services.minio.loadbalancer.server.port=9000
      - traefik.http.middlewares.minio.redirectscheme.scheme=https
      - traefik.http.middlewares.minio.redirectscheme.permanent=true
      - traefik.http.routers.minio.tls=true
      - traefik.http.routers.minio.tls.certresolver=letsencrypt

      - traefik.http.routers.minio-admin.service=minio
      - traefik.http.routers.minio-admin.rule=Host(`${MINIO_ADMIN_DOMAIN}`)
      - traefik.http.services.minio-admin.loadbalancer.server.port=9001
      - traefik.http.middlewares.minio-admin.redirectscheme.scheme=https
      - traefik.http.middlewares.minio-admin.redirectscheme.permanent=true
      - traefik.http.routers.minio-admin.tls=true
      - traefik.http.routers.minio-admin.tls.certresolver=letsencrypt

networks:
  default:
    name: traefik
    external: true

volumes:
  data: